version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "aleksAug2024"
github_repo = "sam-app"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::119254272961:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-YI9flNQWMq7v"
cloudformation_execution_role = "arn:aws:iam::119254272961:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-GgtvNRz7jixA"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-2jt1ztfrmqxz"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::119254272961:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-10mX4zYJhzSG"
cloudformation_execution_role = "arn:aws:iam::119254272961:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-gyOnFcHqpWlu"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-ujskreqq9agq"
image_repository = ""
region = "us-east-1"
